<?php
/**
* @file
* A description of what your module does.
*/
function nfb_washington_mail($key, &$message, $params)
{
    if($key) {
        switch ($key) {
            case 'nfb_wash_meeting_rating':
                $message['subject'] = $params['subject'];
                $message['body'][] = $params['message'];
                break;
            case 'nfb_washington_meeting_update':
                $message['subject'] = $params['subject'];
                $message['body'][] = $params['message'];
                break;
        }
    }
}

/**
 * A&P left out the fact they needed committee chairs and ranking members...
 * A note for whoever maintains this, aks lots of questions of Kyle, John Pare et al, because
 * they don't give denials of what they want often enough.  - Sophie Connell
 */

