<?php
/**
* @file
* A description of what your module does.
*/
function nfb_washington_mail($key, &$message, $params)
{
    switch ($key) {
        case 'nfb_wash_meeting_rating':
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['message'];
            break;
        case 'nfb_washington_meeting_update':
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['message'];
            break;
    }
}

/**
 * A&P left out the fact they needed committee chairs and ranking members...
 * A note for whoever maintains this, aks lots of questions of Kyle, John Pare et al, because
 * they don't give denials of what they want often enough.  - Sophie Connell
 */
function hook_schema()
{
    $spec = [
        'type' => 'int',
        'description' => "If the member is the chairperson",
        'size' => 'tiny',
        'not null' => false,
    ];
    $schema = Database::getConnection()->schema();
    $schema->addField('nfb_washington_committee_mem', 'is_chair', $spec);
    $spec = [
        'type' => 'int',
        'description' => "If the member is the ranking member",
        'size' => 'tiny',
        'not null' => false,
    ];
    $schema->addField('nfb_washington_committee_mem', 'is_ranking', $spec);

}
