<?php
Namespace Drupal\nfb_washington\Form;
use Drupal\nfb_washington\form_factory\form_factory;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
class NewMeetingForm extends FormBase
{
    public $form_factory;
    public function getFormId()
    {return 'washington_sem_new_meeting';}
    public function buildForm(array $form, FormStateInterface $form_state)
    {
        $this->form_factory = new form_factory();
        $this->form_factory->build_new_meeting_time($form, $form_state);
        return $form;
    }
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        // TODO: Implement submitForm() method.
    }
    public function validateForm(array &$form, FormStateInterface $form_state)
    {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }
    public function staterep_refresh(&$form, $form_state)
    {
        \drupal::logger('nfb_washington_ajax_test')->notice(print_r($form['select_rep'], true));
        return $form['select_rep'];
    }
}