<?php
Namespace Drupal\nfb_washington\Form;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\nfb_washington\form_factory\form_factory;
use Drupal\nfb_washington\post_process\new_update_meeting_backend;

class NewMeetingForm extends FormBase
{
    public $form_factory;
    public $post_process;
    public function getFormId()
    {return 'washington_sem_new_meeting';}
    public function buildForm(array $form, FormStateInterface $form_state, $meeting = "new")
    {
        $form['#attached']['library'][] = 'nfb_washington/updatemeeting';
        $this->form_factory = new form_factory();
        $this->form_factory->build_new_meeting_time($form, $form_state, $meeting);
        $this->form_factory = null;
        return $form;
    }
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        $this->post_process = new new_update_meeting_backend();
        \Drupal::logger("nfb_washington")->notice("New/Edit Meeting form submission created by ".\Drupal::currentUser()->getAccountName());
        $this->post_process->backed($form_state);

    }
    public function validateForm(array &$form, FormStateInterface $form_state)
    {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }
    public function staterep_refresh(&$form, $form_state)
    {
        return $form['select_rep'];
    }
}