<?php
Namespace Drupal\nfb_washington\Form;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\nfb_washington\form_factory\form_factory;
use Drupal\nfb_washington\post_process\meeting_backend;

class NewMeetingForm extends FormBase
{
    public $form_factory;
    public $post_process;
    public function getFormId()
    {return 'washington_sem_new_meeting';}
    public function buildForm(array $form, FormStateInterface $form_state, $meeting = "new")
    {
        $this->form_factory = new form_factory();
        $this->form_factory->build_new_meeting_time($form, $form_state, $meeting);
        $this->form_factory = null;
        return $form;
    }
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        $this->post_process = new meeting_backend();
        $this->post_process->meeting_person($form_state);
        $this->post_process = null;
        drupal_set_message($this->t("New Meeting Created"), 'status');
    }
    public function validateForm(array &$form, FormStateInterface $form_state)
    {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }
    public function staterep_refresh(&$form, $form_state)
    {
        return $form['select_rep'];
    }
}